
package com.gratex.perconik.services.activity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IActivitySvc", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IActivitySvc {


    /**
     * 
     * @param activity
     */
    @WebMethod(operationName = "CommitActivity", action = "http://www.gratex.com/PerConIk/IActivitySvc/IActivitySvc/CommitActivity")
    @RequestWrapper(localName = "CommitActivity", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", className = "com.gratex.perconik.services.activity.CommitActivity")
    @ResponseWrapper(localName = "CommitActivityResponse", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", className = "com.gratex.perconik.services.activity.CommitActivityResponse")
    public void commitActivity(
        @WebParam(name = "Activity", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc")
        ActivityDto activity);

    /**
     * 
     * @param guid
     * @return
     *     returns com.gratex.perconik.services.activity.ActivityDto
     */
    @WebMethod(operationName = "GetActivity", action = "http://www.gratex.com/PerConIk/IActivitySvc/IActivitySvc/GetActivity")
    @WebResult(name = "GetActivityResult", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc")
    @RequestWrapper(localName = "GetActivity", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", className = "com.gratex.perconik.services.activity.GetActivity")
    @ResponseWrapper(localName = "GetActivityResponse", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", className = "com.gratex.perconik.services.activity.GetActivityResponse")
    public ActivityDto getActivity(
        @WebParam(name = "guid", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc")
        String guid);

    /**
     * 
     * @param filter
     * @return
     *     returns com.gratex.perconik.services.activity.ArrayOfActivityDto
     */
    @WebMethod(operationName = "GetActivities", action = "http://www.gratex.com/PerConIk/IActivitySvc/IActivitySvc/GetActivities")
    @WebResult(name = "GetActivitiesResult", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc")
    @RequestWrapper(localName = "GetActivities", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", className = "com.gratex.perconik.services.activity.GetActivities")
    @ResponseWrapper(localName = "GetActivitiesResponse", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", className = "com.gratex.perconik.services.activity.GetActivitiesResponse")
    public ArrayOfActivityDto getActivities(
        @WebParam(name = "filter", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc")
        ActivityFilter filter);

}
