
package com.gratex.perconik.services.activity;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVsActivityWatcherService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVsActivityWatcherService {


    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeStateChangeResponse>
     */
    @WebMethod(operationName = "NotifyIdeStateChange", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeStateChange")
    @RequestWrapper(localName = "NotifyIdeStateChange", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeStateChange")
    @ResponseWrapper(localName = "NotifyIdeStateChangeResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeStateChangeResponse")
    public Response<NotifyIdeStateChangeResponse> notifyIdeStateChangeAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeStateChangeDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeStateChange", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeStateChange")
    @RequestWrapper(localName = "NotifyIdeStateChange", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeStateChange")
    @ResponseWrapper(localName = "NotifyIdeStateChangeResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeStateChangeResponse")
    public Future<?> notifyIdeStateChangeAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeStateChangeDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeStateChangeResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeStateChange", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeStateChange")
    @RequestWrapper(localName = "NotifyIdeStateChange", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeStateChange")
    @ResponseWrapper(localName = "NotifyIdeStateChangeResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeStateChangeResponse")
    public void notifyIdeStateChange(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeStateChangeDto eventDto);

    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeDocumentOperationResponse>
     */
    @WebMethod(operationName = "NotifyIdeDocumentOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeDocumentOperation")
    @RequestWrapper(localName = "NotifyIdeDocumentOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeDocumentOperation")
    @ResponseWrapper(localName = "NotifyIdeDocumentOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeDocumentOperationResponse")
    public Response<NotifyIdeDocumentOperationResponse> notifyIdeDocumentOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeDocumentOperationDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeDocumentOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeDocumentOperation")
    @RequestWrapper(localName = "NotifyIdeDocumentOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeDocumentOperation")
    @ResponseWrapper(localName = "NotifyIdeDocumentOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeDocumentOperationResponse")
    public Future<?> notifyIdeDocumentOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeDocumentOperationDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeDocumentOperationResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeDocumentOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeDocumentOperation")
    @RequestWrapper(localName = "NotifyIdeDocumentOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeDocumentOperation")
    @ResponseWrapper(localName = "NotifyIdeDocumentOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeDocumentOperationResponse")
    public void notifyIdeDocumentOperation(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeDocumentOperationDto eventDto);

    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeProjectOperationResponse>
     */
    @WebMethod(operationName = "NotifyIdeProjectOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeProjectOperation")
    @RequestWrapper(localName = "NotifyIdeProjectOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeProjectOperation")
    @ResponseWrapper(localName = "NotifyIdeProjectOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeProjectOperationResponse")
    public Response<NotifyIdeProjectOperationResponse> notifyIdeProjectOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeProjectOperationDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeProjectOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeProjectOperation")
    @RequestWrapper(localName = "NotifyIdeProjectOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeProjectOperation")
    @ResponseWrapper(localName = "NotifyIdeProjectOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeProjectOperationResponse")
    public Future<?> notifyIdeProjectOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeProjectOperationDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeProjectOperationResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeProjectOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeProjectOperation")
    @RequestWrapper(localName = "NotifyIdeProjectOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeProjectOperation")
    @ResponseWrapper(localName = "NotifyIdeProjectOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeProjectOperationResponse")
    public void notifyIdeProjectOperation(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeProjectOperationDto eventDto);

    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeCheckinResponse>
     */
    @WebMethod(operationName = "NotifyIdeCheckin", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCheckin")
    @RequestWrapper(localName = "NotifyIdeCheckin", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCheckin")
    @ResponseWrapper(localName = "NotifyIdeCheckinResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCheckinResponse")
    public Response<NotifyIdeCheckinResponse> notifyIdeCheckinAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCheckinDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeCheckin", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCheckin")
    @RequestWrapper(localName = "NotifyIdeCheckin", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCheckin")
    @ResponseWrapper(localName = "NotifyIdeCheckinResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCheckinResponse")
    public Future<?> notifyIdeCheckinAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCheckinDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeCheckinResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeCheckin", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCheckin")
    @RequestWrapper(localName = "NotifyIdeCheckin", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCheckin")
    @ResponseWrapper(localName = "NotifyIdeCheckinResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCheckinResponse")
    public void notifyIdeCheckin(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCheckinDto eventDto);

    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeCodeOperationResponse>
     */
    @WebMethod(operationName = "NotifyIdeCodeOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCodeOperation")
    @RequestWrapper(localName = "NotifyIdeCodeOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeOperation")
    @ResponseWrapper(localName = "NotifyIdeCodeOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeOperationResponse")
    public Response<NotifyIdeCodeOperationResponse> notifyIdeCodeOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCodeOperationDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeCodeOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCodeOperation")
    @RequestWrapper(localName = "NotifyIdeCodeOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeOperation")
    @ResponseWrapper(localName = "NotifyIdeCodeOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeOperationResponse")
    public Future<?> notifyIdeCodeOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCodeOperationDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeCodeOperationResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeCodeOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCodeOperation")
    @RequestWrapper(localName = "NotifyIdeCodeOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeOperation")
    @ResponseWrapper(localName = "NotifyIdeCodeOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeOperationResponse")
    public void notifyIdeCodeOperation(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCodeOperationDto eventDto);

    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeFindOperationResponse>
     */
    @WebMethod(operationName = "NotifyIdeFindOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeFindOperation")
    @RequestWrapper(localName = "NotifyIdeFindOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeFindOperation")
    @ResponseWrapper(localName = "NotifyIdeFindOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeFindOperationResponse")
    public Response<NotifyIdeFindOperationResponse> notifyIdeFindOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeFindOperationDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeFindOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeFindOperation")
    @RequestWrapper(localName = "NotifyIdeFindOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeFindOperation")
    @ResponseWrapper(localName = "NotifyIdeFindOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeFindOperationResponse")
    public Future<?> notifyIdeFindOperationAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeFindOperationDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeFindOperationResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeFindOperation", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeFindOperation")
    @RequestWrapper(localName = "NotifyIdeFindOperation", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeFindOperation")
    @ResponseWrapper(localName = "NotifyIdeFindOperationResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeFindOperationResponse")
    public void notifyIdeFindOperation(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeFindOperationDto eventDto);

    /**
     * 
     * @param eventDto
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.activity.NotifyIdeCodeElementEventResponse>
     */
    @WebMethod(operationName = "NotifyIdeCodeElementEvent", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCodeElementEvent")
    @RequestWrapper(localName = "NotifyIdeCodeElementEvent", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeElementEvent")
    @ResponseWrapper(localName = "NotifyIdeCodeElementEventResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeElementEventResponse")
    public Response<NotifyIdeCodeElementEventResponse> notifyIdeCodeElementEventAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCodeElementEventDto eventDto);

    /**
     * 
     * @param asyncHandler
     * @param eventDto
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NotifyIdeCodeElementEvent", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCodeElementEvent")
    @RequestWrapper(localName = "NotifyIdeCodeElementEvent", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeElementEvent")
    @ResponseWrapper(localName = "NotifyIdeCodeElementEventResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeElementEventResponse")
    public Future<?> notifyIdeCodeElementEventAsync(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCodeElementEventDto eventDto,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NotifyIdeCodeElementEventResponse> asyncHandler);

    /**
     * 
     * @param eventDto
     */
    @WebMethod(operationName = "NotifyIdeCodeElementEvent", action = "http://tempuri.org/IVsActivityWatcherService/NotifyIdeCodeElementEvent")
    @RequestWrapper(localName = "NotifyIdeCodeElementEvent", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeElementEvent")
    @ResponseWrapper(localName = "NotifyIdeCodeElementEventResponse", targetNamespace = "http://tempuri.org/", className = "com.gratex.perconik.services.activity.NotifyIdeCodeElementEventResponse")
    public void notifyIdeCodeElementEvent(
        @WebParam(name = "eventDto", targetNamespace = "http://tempuri.org/")
        IdeCodeElementEventDto eventDto);

}
