
package com.gratex.perconik.services.activity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VsActivityWatcherService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:7979/VsActivityWatcherService?wsdl")
public class VsActivityWatcherService
    extends Service
{

    private final static URL VSACTIVITYWATCHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException VSACTIVITYWATCHERSERVICE_EXCEPTION;
    private final static QName VSACTIVITYWATCHERSERVICE_QNAME = new QName("http://tempuri.org/", "VsActivityWatcherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7979/VsActivityWatcherService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VSACTIVITYWATCHERSERVICE_WSDL_LOCATION = url;
        VSACTIVITYWATCHERSERVICE_EXCEPTION = e;
    }

    public VsActivityWatcherService() {
        super(__getWsdlLocation(), VSACTIVITYWATCHERSERVICE_QNAME);
    }

    public VsActivityWatcherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VSACTIVITYWATCHERSERVICE_QNAME, features);
    }

    public VsActivityWatcherService(URL wsdlLocation) {
        super(wsdlLocation, VSACTIVITYWATCHERSERVICE_QNAME);
    }

    public VsActivityWatcherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VSACTIVITYWATCHERSERVICE_QNAME, features);
    }

    public VsActivityWatcherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VsActivityWatcherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVsActivityWatcherService
     */
    @WebEndpoint(name = "NetNamedPipeBinding_IVsActivityWatcherService")
    public IVsActivityWatcherService getNetNamedPipeBindingIVsActivityWatcherService() {
        return super.getPort(new QName("http://tempuri.org/", "NetNamedPipeBinding_IVsActivityWatcherService"), IVsActivityWatcherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVsActivityWatcherService
     */
    @WebEndpoint(name = "NetNamedPipeBinding_IVsActivityWatcherService")
    public IVsActivityWatcherService getNetNamedPipeBindingIVsActivityWatcherService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "NetNamedPipeBinding_IVsActivityWatcherService"), IVsActivityWatcherService.class, features);
    }

    /**
     * 
     * @return
     *     returns IVsActivityWatcherService
     */
    @WebEndpoint(name = "BasicHttpBinding_IVsActivityWatcherService")
    public IVsActivityWatcherService getBasicHttpBindingIVsActivityWatcherService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IVsActivityWatcherService"), IVsActivityWatcherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVsActivityWatcherService
     */
    @WebEndpoint(name = "BasicHttpBinding_IVsActivityWatcherService")
    public IVsActivityWatcherService getBasicHttpBindingIVsActivityWatcherService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IVsActivityWatcherService"), IVsActivityWatcherService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VSACTIVITYWATCHERSERVICE_EXCEPTION!= null) {
            throw VSACTIVITYWATCHERSERVICE_EXCEPTION;
        }
        return VSACTIVITYWATCHERSERVICE_WSDL_LOCATION;
    }

}
