
package com.gratex.perconik.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActivitySvc", targetNamespace = "http://www.gratex.com/PerConIk/IActivitySvc", wsdlLocation = "file:/D:/workspace/perconik/com.gratex.perconik.services/ActivitySvc.svc.wsdl")
public class ActivitySvc
    extends Service
{

    private final static URL ACTIVITYSVC_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYSVC_EXCEPTION;
    private final static QName ACTIVITYSVC_QNAME = new QName("http://www.gratex.com/PerConIk/IActivitySvc", "ActivitySvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/perconik/com.gratex.perconik.services/ActivitySvc.svc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYSVC_WSDL_LOCATION = url;
        ACTIVITYSVC_EXCEPTION = e;
    }

    public ActivitySvc() {
        super(__getWsdlLocation(), ACTIVITYSVC_QNAME);
    }

    public ActivitySvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYSVC_QNAME, features);
    }

    public ActivitySvc(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYSVC_QNAME);
    }

    public ActivitySvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYSVC_QNAME, features);
    }

    public ActivitySvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivitySvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IActivitySvc
     */
    @WebEndpoint(name = "BasicHttpBinding_IActivitySvc")
    public IActivitySvc getBasicHttpBindingIActivitySvc() {
        return super.getPort(new QName("http://www.gratex.com/PerConIk/IActivitySvc", "BasicHttpBinding_IActivitySvc"), IActivitySvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IActivitySvc
     */
    @WebEndpoint(name = "BasicHttpBinding_IActivitySvc")
    public IActivitySvc getBasicHttpBindingIActivitySvc(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.gratex.com/PerConIk/IActivitySvc", "BasicHttpBinding_IActivitySvc"), IActivitySvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYSVC_EXCEPTION!= null) {
            throw ACTIVITYSVC_EXCEPTION;
        }
        return ACTIVITYSVC_WSDL_LOCATION;
    }

}
