
package com.gratex.perconik.services;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import com.gratex.perconik.services.itm.AddInformationTagResponse;
import com.gratex.perconik.services.itm.ArrayOfInformationTag;
import com.gratex.perconik.services.itm.AstRcsContextConstraint;
import com.gratex.perconik.services.itm.DeleteInformationTagResponse;
import com.gratex.perconik.services.itm.EventListenerDetails;
import com.gratex.perconik.services.itm.ExecuteSparqlQueryResponse;
import com.gratex.perconik.services.itm.GetInformationTagOfVersionResponse;
import com.gratex.perconik.services.itm.GetInformationTagResponse;
import com.gratex.perconik.services.itm.GetInformationTagsCountResponse;
import com.gratex.perconik.services.itm.GetInformationTagsHistoricallyResponse;
import com.gratex.perconik.services.itm.GetInformationTagsResponse;
import com.gratex.perconik.services.itm.GetInformationTagsUriResponse;
import com.gratex.perconik.services.itm.InformationTag;
import com.gratex.perconik.services.itm.InformationTagConstraint;
import com.gratex.perconik.services.itm.RecoverInformationTagResponse;
import com.gratex.perconik.services.itm.RegisterEventListenerResponse;
import com.gratex.perconik.services.itm.UnregisterEventListenerResponse;
import com.gratex.perconik.services.itm.UpdateInformationTagResponse;
import com.gratex.perconik.services.itm.serialization.arrays.ArrayOfArrayOfKeyValueOfstringRDFDataWYX0VZP7;
import com.gratex.perconik.services.itm.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IITMaintenance", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
@XmlSeeAlso({
    com.gratex.perconik.services.itm.ObjectFactory.class,
    com.gratex.perconik.services.itm.serialization.arrays.ObjectFactory.class,
    com.gratex.perconik.services.itm.serialization.ObjectFactory.class,
    com.gratex.perconik.services.itm.serialization.queries.ObjectFactory.class
})
public interface IITMaintenance {


    /**
     * 
     * @param informationTag
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.AddInformationTagResponse>
     */
    @WebMethod(operationName = "AddInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/AddInformationTag")
    @RequestWrapper(localName = "AddInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTag")
    @ResponseWrapper(localName = "AddInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTagResponse")
    public Response<AddInformationTagResponse> addInformationTagAsync(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag);

    /**
     * 
     * @param asyncHandler
     * @param informationTag
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "AddInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/AddInformationTag")
    @RequestWrapper(localName = "AddInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTag")
    @ResponseWrapper(localName = "AddInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTagResponse")
    public Future<?> addInformationTagAsync(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AddInformationTagResponse> asyncHandler);

    /**
     * 
     * @param informationTag
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/AddInformationTag")
    @WebResult(name = "AddInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "AddInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTag")
    @ResponseWrapper(localName = "AddInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTagResponse")
    public String addInformationTag(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag);

    /**
     * 
     * @param informationTag
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.UpdateInformationTagResponse>
     */
    @WebMethod(operationName = "UpdateInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UpdateInformationTag")
    @RequestWrapper(localName = "UpdateInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTag")
    @ResponseWrapper(localName = "UpdateInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTagResponse")
    public Response<UpdateInformationTagResponse> updateInformationTagAsync(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag);

    /**
     * 
     * @param asyncHandler
     * @param informationTag
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UpdateInformationTag")
    @RequestWrapper(localName = "UpdateInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTag")
    @ResponseWrapper(localName = "UpdateInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTagResponse")
    public Future<?> updateInformationTagAsync(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdateInformationTagResponse> asyncHandler);

    /**
     * 
     * @param informationTag
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UpdateInformationTag")
    @WebResult(name = "UpdateInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "UpdateInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTag")
    @ResponseWrapper(localName = "UpdateInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTagResponse")
    public Boolean updateInformationTag(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag);

    /**
     * 
     * @param uri
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.DeleteInformationTagResponse>
     */
    @WebMethod(operationName = "DeleteInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/DeleteInformationTag")
    @RequestWrapper(localName = "DeleteInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTag")
    @ResponseWrapper(localName = "DeleteInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTagResponse")
    public Response<DeleteInformationTagResponse> deleteInformationTagAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param asyncHandler
     * @param uri
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/DeleteInformationTag")
    @RequestWrapper(localName = "DeleteInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTag")
    @ResponseWrapper(localName = "DeleteInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTagResponse")
    public Future<?> deleteInformationTagAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteInformationTagResponse> asyncHandler);

    /**
     * 
     * @param uri
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/DeleteInformationTag")
    @WebResult(name = "DeleteInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "DeleteInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTag")
    @ResponseWrapper(localName = "DeleteInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTagResponse")
    public Boolean deleteInformationTag(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param uri
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.RecoverInformationTagResponse>
     */
    @WebMethod(operationName = "RecoverInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RecoverInformationTag")
    @RequestWrapper(localName = "RecoverInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTag")
    @ResponseWrapper(localName = "RecoverInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTagResponse")
    public Response<RecoverInformationTagResponse> recoverInformationTagAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param asyncHandler
     * @param uri
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RecoverInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RecoverInformationTag")
    @RequestWrapper(localName = "RecoverInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTag")
    @ResponseWrapper(localName = "RecoverInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTagResponse")
    public Future<?> recoverInformationTagAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RecoverInformationTagResponse> asyncHandler);

    /**
     * 
     * @param uri
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RecoverInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RecoverInformationTag")
    @WebResult(name = "RecoverInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "RecoverInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTag")
    @ResponseWrapper(localName = "RecoverInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTagResponse")
    public Boolean recoverInformationTag(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param uri
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.GetInformationTagResponse>
     */
    @WebMethod(operationName = "GetInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTag")
    @RequestWrapper(localName = "GetInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTag")
    @ResponseWrapper(localName = "GetInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagResponse")
    public Response<GetInformationTagResponse> getInformationTagAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param asyncHandler
     * @param uri
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTag")
    @RequestWrapper(localName = "GetInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTag")
    @ResponseWrapper(localName = "GetInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagResponse")
    public Future<?> getInformationTagAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetInformationTagResponse> asyncHandler);

    /**
     * 
     * @param uri
     * @return
     *     returns com.gratex.perconik.services.itm.InformationTag
     */
    @WebMethod(operationName = "GetInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTag")
    @WebResult(name = "GetInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTag")
    @ResponseWrapper(localName = "GetInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagResponse")
    public InformationTag getInformationTag(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param uri
     * @param version
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.GetInformationTagOfVersionResponse>
     */
    @WebMethod(operationName = "GetInformationTagOfVersion", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagOfVersion")
    @RequestWrapper(localName = "GetInformationTagOfVersion", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersion")
    @ResponseWrapper(localName = "GetInformationTagOfVersionResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersionResponse")
    public Response<GetInformationTagOfVersionResponse> getInformationTagOfVersionAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "version", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Integer version);

    /**
     * 
     * @param asyncHandler
     * @param uri
     * @param version
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetInformationTagOfVersion", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagOfVersion")
    @RequestWrapper(localName = "GetInformationTagOfVersion", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersion")
    @ResponseWrapper(localName = "GetInformationTagOfVersionResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersionResponse")
    public Future<?> getInformationTagOfVersionAsync(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "version", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Integer version,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetInformationTagOfVersionResponse> asyncHandler);

    /**
     * 
     * @param uri
     * @param version
     * @return
     *     returns com.gratex.perconik.services.itm.InformationTag
     */
    @WebMethod(operationName = "GetInformationTagOfVersion", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagOfVersion")
    @WebResult(name = "GetInformationTagOfVersionResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagOfVersion", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersion")
    @ResponseWrapper(localName = "GetInformationTagOfVersionResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersionResponse")
    public InformationTag getInformationTagOfVersion(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "version", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Integer version);

    /**
     * 
     * @param astRcsContextConstraint
     * @param getDeleted
     * @param targetUries
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.GetInformationTagsUriResponse>
     */
    @WebMethod(operationName = "GetInformationTagsUri", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsUri")
    @RequestWrapper(localName = "GetInformationTagsUri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUri")
    @ResponseWrapper(localName = "GetInformationTagsUriResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUriResponse")
    public Response<GetInformationTagsUriResponse> getInformationTagsUriAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "astRcsContextConstraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        AstRcsContextConstraint astRcsContextConstraint);

    /**
     * 
     * @param astRcsContextConstraint
     * @param getDeleted
     * @param asyncHandler
     * @param targetUries
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetInformationTagsUri", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsUri")
    @RequestWrapper(localName = "GetInformationTagsUri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUri")
    @ResponseWrapper(localName = "GetInformationTagsUriResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUriResponse")
    public Future<?> getInformationTagsUriAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "astRcsContextConstraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        AstRcsContextConstraint astRcsContextConstraint,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetInformationTagsUriResponse> asyncHandler);

    /**
     * 
     * @param astRcsContextConstraint
     * @param getDeleted
     * @param targetUries
     * @return
     *     returns com.gratex.perconik.services.itm.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetInformationTagsUri", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsUri")
    @WebResult(name = "GetInformationTagsUriResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagsUri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUri")
    @ResponseWrapper(localName = "GetInformationTagsUriResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUriResponse")
    public ArrayOfstring getInformationTagsUri(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "astRcsContextConstraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        AstRcsContextConstraint astRcsContextConstraint);

    /**
     * 
     * @param getDeleted
     * @param constraint
     * @param targetUries
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.GetInformationTagsCountResponse>
     */
    @WebMethod(operationName = "GetInformationTagsCount", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsCount")
    @RequestWrapper(localName = "GetInformationTagsCount", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsCount")
    @ResponseWrapper(localName = "GetInformationTagsCountResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsCountResponse")
    public Response<GetInformationTagsCountResponse> getInformationTagsCountAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint);

    /**
     * 
     * @param getDeleted
     * @param asyncHandler
     * @param constraint
     * @param targetUries
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetInformationTagsCount", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsCount")
    @RequestWrapper(localName = "GetInformationTagsCount", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsCount")
    @ResponseWrapper(localName = "GetInformationTagsCountResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsCountResponse")
    public Future<?> getInformationTagsCountAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetInformationTagsCountResponse> asyncHandler);

    /**
     * 
     * @param getDeleted
     * @param constraint
     * @param targetUries
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetInformationTagsCount", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsCount")
    @WebResult(name = "GetInformationTagsCountResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagsCount", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsCount")
    @ResponseWrapper(localName = "GetInformationTagsCountResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsCountResponse")
    public Long getInformationTagsCount(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint);

    /**
     * 
     * @param getDeleted
     * @param constraint
     * @param targetUries
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.GetInformationTagsResponse>
     */
    @WebMethod(operationName = "GetInformationTags", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTags")
    @RequestWrapper(localName = "GetInformationTags", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTags")
    @ResponseWrapper(localName = "GetInformationTagsResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsResponse")
    public Response<GetInformationTagsResponse> getInformationTagsAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint);

    /**
     * 
     * @param getDeleted
     * @param asyncHandler
     * @param constraint
     * @param targetUries
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetInformationTags", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTags")
    @RequestWrapper(localName = "GetInformationTags", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTags")
    @ResponseWrapper(localName = "GetInformationTagsResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsResponse")
    public Future<?> getInformationTagsAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetInformationTagsResponse> asyncHandler);

    /**
     * 
     * @param getDeleted
     * @param constraint
     * @param targetUries
     * @return
     *     returns com.gratex.perconik.services.itm.ArrayOfInformationTag
     */
    @WebMethod(operationName = "GetInformationTags", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTags")
    @WebResult(name = "GetInformationTagsResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTags", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTags")
    @ResponseWrapper(localName = "GetInformationTagsResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsResponse")
    public ArrayOfInformationTag getInformationTags(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint);

    /**
     * 
     * @param constraint
     * @param targetUries
     * @param onlyNewestVersions
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.GetInformationTagsHistoricallyResponse>
     */
    @WebMethod(operationName = "GetInformationTagsHistorically", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsHistorically")
    @RequestWrapper(localName = "GetInformationTagsHistorically", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistorically")
    @ResponseWrapper(localName = "GetInformationTagsHistoricallyResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistoricallyResponse")
    public Response<GetInformationTagsHistoricallyResponse> getInformationTagsHistoricallyAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint,
        @WebParam(name = "onlyNewestVersions", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean onlyNewestVersions);

    /**
     * 
     * @param asyncHandler
     * @param constraint
     * @param targetUries
     * @param onlyNewestVersions
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetInformationTagsHistorically", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsHistorically")
    @RequestWrapper(localName = "GetInformationTagsHistorically", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistorically")
    @ResponseWrapper(localName = "GetInformationTagsHistoricallyResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistoricallyResponse")
    public Future<?> getInformationTagsHistoricallyAsync(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint,
        @WebParam(name = "onlyNewestVersions", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean onlyNewestVersions,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetInformationTagsHistoricallyResponse> asyncHandler);

    /**
     * 
     * @param constraint
     * @param targetUries
     * @param onlyNewestVersions
     * @return
     *     returns com.gratex.perconik.services.itm.ArrayOfInformationTag
     */
    @WebMethod(operationName = "GetInformationTagsHistorically", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsHistorically")
    @WebResult(name = "GetInformationTagsHistoricallyResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagsHistorically", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistorically")
    @ResponseWrapper(localName = "GetInformationTagsHistoricallyResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistoricallyResponse")
    public ArrayOfInformationTag getInformationTagsHistorically(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint,
        @WebParam(name = "onlyNewestVersions", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean onlyNewestVersions);

    /**
     * 
     * @param eventListenerDetails
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.RegisterEventListenerResponse>
     */
    @WebMethod(operationName = "RegisterEventListener", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RegisterEventListener")
    @RequestWrapper(localName = "RegisterEventListener", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RegisterEventListener")
    @ResponseWrapper(localName = "RegisterEventListenerResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RegisterEventListenerResponse")
    public Response<RegisterEventListenerResponse> registerEventListenerAsync(
        @WebParam(name = "eventListenerDetails", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        EventListenerDetails eventListenerDetails);

    /**
     * 
     * @param eventListenerDetails
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RegisterEventListener", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RegisterEventListener")
    @RequestWrapper(localName = "RegisterEventListener", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RegisterEventListener")
    @ResponseWrapper(localName = "RegisterEventListenerResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RegisterEventListenerResponse")
    public Future<?> registerEventListenerAsync(
        @WebParam(name = "eventListenerDetails", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        EventListenerDetails eventListenerDetails,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RegisterEventListenerResponse> asyncHandler);

    /**
     * 
     * @param eventListenerDetails
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterEventListener", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RegisterEventListener")
    @WebResult(name = "RegisterEventListenerResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "RegisterEventListener", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RegisterEventListener")
    @ResponseWrapper(localName = "RegisterEventListenerResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RegisterEventListenerResponse")
    public String registerEventListener(
        @WebParam(name = "eventListenerDetails", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        EventListenerDetails eventListenerDetails);

    /**
     * 
     * @param eventId
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.UnregisterEventListenerResponse>
     */
    @WebMethod(operationName = "UnregisterEventListener", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UnregisterEventListener")
    @RequestWrapper(localName = "UnregisterEventListener", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UnregisterEventListener")
    @ResponseWrapper(localName = "UnregisterEventListenerResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UnregisterEventListenerResponse")
    public Response<UnregisterEventListenerResponse> unregisterEventListenerAsync(
        @WebParam(name = "eventId", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String eventId);

    /**
     * 
     * @param eventId
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UnregisterEventListener", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UnregisterEventListener")
    @RequestWrapper(localName = "UnregisterEventListener", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UnregisterEventListener")
    @ResponseWrapper(localName = "UnregisterEventListenerResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UnregisterEventListenerResponse")
    public Future<?> unregisterEventListenerAsync(
        @WebParam(name = "eventId", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String eventId,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UnregisterEventListenerResponse> asyncHandler);

    /**
     * 
     * @param eventId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UnregisterEventListener", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UnregisterEventListener")
    @WebResult(name = "UnregisterEventListenerResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "UnregisterEventListener", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UnregisterEventListener")
    @ResponseWrapper(localName = "UnregisterEventListenerResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UnregisterEventListenerResponse")
    public Boolean unregisterEventListener(
        @WebParam(name = "eventId", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String eventId);

    /**
     * 
     * @param query
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.itm.ExecuteSparqlQueryResponse>
     */
    @WebMethod(operationName = "ExecuteSparqlQuery", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/ExecuteSparqlQuery")
    @RequestWrapper(localName = "ExecuteSparqlQuery", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQuery")
    @ResponseWrapper(localName = "ExecuteSparqlQueryResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQueryResponse")
    public Response<ExecuteSparqlQueryResponse> executeSparqlQueryAsync(
        @WebParam(name = "query", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String query);

    /**
     * 
     * @param query
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ExecuteSparqlQuery", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/ExecuteSparqlQuery")
    @RequestWrapper(localName = "ExecuteSparqlQuery", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQuery")
    @ResponseWrapper(localName = "ExecuteSparqlQueryResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQueryResponse")
    public Future<?> executeSparqlQueryAsync(
        @WebParam(name = "query", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String query,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ExecuteSparqlQueryResponse> asyncHandler);

    /**
     * 
     * @param query
     * @return
     *     returns com.gratex.perconik.services.itm.serialization.arrays.ArrayOfArrayOfKeyValueOfstringRDFDataWYX0VZP7
     */
    @WebMethod(operationName = "ExecuteSparqlQuery", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/ExecuteSparqlQuery")
    @WebResult(name = "ExecuteSparqlQueryResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "ExecuteSparqlQuery", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQuery")
    @ResponseWrapper(localName = "ExecuteSparqlQueryResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQueryResponse")
    public ArrayOfArrayOfKeyValueOfstringRDFDataWYX0VZP7 executeSparqlQuery(
        @WebParam(name = "query", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String query);

}
