
package com.gratex.perconik.services;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

import com.gratex.perconik.services.tag.AnonymousGetLineCommentFormatsResponse;
import com.gratex.perconik.services.tag.AnonymousGetTagProfileResponse;
import com.gratex.perconik.services.tag.AnonymousSearchTagProfileResponse;
import com.gratex.perconik.services.tag.GetLineCommentFormatsRequest;
import com.gratex.perconik.services.tag.GetLineCommentFormatsResponse;
import com.gratex.perconik.services.tag.GetTagProfileRequest;
import com.gratex.perconik.services.tag.GetTagProfileResponse;
import com.gratex.perconik.services.tag.ObjectFactory;
import com.gratex.perconik.services.tag.SearchTagProfileRequest;
import com.gratex.perconik.services.tag.SearchTagProfileResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITagProfileWcfSvc", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITagProfileWcfSvc {


    /**
     * 
     * @param req
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.tag.AnonymousGetTagProfileResponse>
     */
    @WebMethod(operationName = "GetTagProfile", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/GetTagProfile")
    @RequestWrapper(localName = "GetTagProfile", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetTagProfile")
    @ResponseWrapper(localName = "GetTagProfileResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetTagProfileResponse")
    public Response<AnonymousGetTagProfileResponse> getTagProfileAsync(
        @WebParam(name = "Req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        GetTagProfileRequest req);

    /**
     * 
     * @param asyncHandler
     * @param req
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetTagProfile", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/GetTagProfile")
    @RequestWrapper(localName = "GetTagProfile", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetTagProfile")
    @ResponseWrapper(localName = "GetTagProfileResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetTagProfileResponse")
    public Future<?> getTagProfileAsync(
        @WebParam(name = "Req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        GetTagProfileRequest req,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AnonymousGetTagProfileResponse> asyncHandler);

    /**
     * 
     * @param req
     * @return
     *     returns com.gratex.perconik.services.tag.GetTagProfileResponse
     */
    @WebMethod(operationName = "GetTagProfile", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/GetTagProfile")
    @WebResult(name = "GetTagProfileResult", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
    @RequestWrapper(localName = "GetTagProfile", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetTagProfile")
    @ResponseWrapper(localName = "GetTagProfileResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetTagProfileResponse")
    public GetTagProfileResponse getTagProfile(
        @WebParam(name = "Req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        GetTagProfileRequest req);

    /**
     * 
     * @param req
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.tag.AnonymousSearchTagProfileResponse>
     */
    @WebMethod(operationName = "SearchTagProfile", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/SearchTagProfile")
    @RequestWrapper(localName = "SearchTagProfile", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousSearchTagProfile")
    @ResponseWrapper(localName = "SearchTagProfileResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousSearchTagProfileResponse")
    public Response<AnonymousSearchTagProfileResponse> searchTagProfileAsync(
        @WebParam(name = "Req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        SearchTagProfileRequest req);

    /**
     * 
     * @param asyncHandler
     * @param req
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchTagProfile", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/SearchTagProfile")
    @RequestWrapper(localName = "SearchTagProfile", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousSearchTagProfile")
    @ResponseWrapper(localName = "SearchTagProfileResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousSearchTagProfileResponse")
    public Future<?> searchTagProfileAsync(
        @WebParam(name = "Req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        SearchTagProfileRequest req,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AnonymousSearchTagProfileResponse> asyncHandler);

    /**
     * 
     * @param req
     * @return
     *     returns com.gratex.perconik.services.tag.SearchTagProfileResponse
     */
    @WebMethod(operationName = "SearchTagProfile", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/SearchTagProfile")
    @WebResult(name = "SearchTagProfileResult", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
    @RequestWrapper(localName = "SearchTagProfile", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousSearchTagProfile")
    @ResponseWrapper(localName = "SearchTagProfileResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousSearchTagProfileResponse")
    public SearchTagProfileResponse searchTagProfile(
        @WebParam(name = "Req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        SearchTagProfileRequest req);

    /**
     * 
     * @param req
     * @return
     *     returns javax.xml.ws.Response<com.gratex.perconik.services.tag.AnonymousGetLineCommentFormatsResponse>
     */
    @WebMethod(operationName = "GetLineCommentFormats", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/GetLineCommentFormats")
    @RequestWrapper(localName = "GetLineCommentFormats", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetLineCommentFormats")
    @ResponseWrapper(localName = "GetLineCommentFormatsResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetLineCommentFormatsResponse")
    public Response<AnonymousGetLineCommentFormatsResponse> getLineCommentFormatsAsync(
        @WebParam(name = "req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        GetLineCommentFormatsRequest req);

    /**
     * 
     * @param asyncHandler
     * @param req
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetLineCommentFormats", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/GetLineCommentFormats")
    @RequestWrapper(localName = "GetLineCommentFormats", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetLineCommentFormats")
    @ResponseWrapper(localName = "GetLineCommentFormatsResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetLineCommentFormatsResponse")
    public Future<?> getLineCommentFormatsAsync(
        @WebParam(name = "req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        GetLineCommentFormatsRequest req,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AnonymousGetLineCommentFormatsResponse> asyncHandler);

    /**
     * 
     * @param req
     * @return
     *     returns com.gratex.perconik.services.tag.GetLineCommentFormatsResponse
     */
    @WebMethod(operationName = "GetLineCommentFormats", action = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc/ITagProfileWcfSvc/GetLineCommentFormats")
    @WebResult(name = "GetLineCommentFormatsResult", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
    @RequestWrapper(localName = "GetLineCommentFormats", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetLineCommentFormats")
    @ResponseWrapper(localName = "GetLineCommentFormatsResponse", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc", className = "com.gratex.perconik.services.tag.AnonymousGetLineCommentFormatsResponse")
    public GetLineCommentFormatsResponse getLineCommentFormats(
        @WebParam(name = "req", targetNamespace = "http://www.gratex.com/PerConIk/TagAdm/ITagProfileWcfSvc")
        GetLineCommentFormatsRequest req);

}
