
package com.gratex.perconik.services.itm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IITMaintenance", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IITMaintenance {


    /**
     * 
     * @param informationTag
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/AddInformationTag")
    @WebResult(name = "AddInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "AddInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTag")
    @ResponseWrapper(localName = "AddInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.AddInformationTagResponse")
    public String addInformationTag(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag);

    /**
     * 
     * @param informationTag
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/UpdateInformationTag")
    @WebResult(name = "UpdateInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "UpdateInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTag")
    @ResponseWrapper(localName = "UpdateInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.UpdateInformationTagResponse")
    public Boolean updateInformationTag(
        @WebParam(name = "informationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTag informationTag);

    /**
     * 
     * @param uri
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/DeleteInformationTag")
    @WebResult(name = "DeleteInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "DeleteInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTag")
    @ResponseWrapper(localName = "DeleteInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.DeleteInformationTagResponse")
    public Boolean deleteInformationTag(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param uri
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RecoverInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/RecoverInformationTag")
    @WebResult(name = "RecoverInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "RecoverInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTag")
    @ResponseWrapper(localName = "RecoverInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.RecoverInformationTagResponse")
    public Boolean recoverInformationTag(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param uri
     * @return
     *     returns com.gratex.perconik.services.itm.InformationTag
     */
    @WebMethod(operationName = "GetInformationTag", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTag")
    @WebResult(name = "GetInformationTagResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTag", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTag")
    @ResponseWrapper(localName = "GetInformationTagResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagResponse")
    public InformationTag getInformationTag(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri);

    /**
     * 
     * @param uri
     * @param version
     * @return
     *     returns com.gratex.perconik.services.itm.InformationTag
     */
    @WebMethod(operationName = "GetInformationTagOfVersion", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagOfVersion")
    @WebResult(name = "GetInformationTagOfVersionResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagOfVersion", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersion")
    @ResponseWrapper(localName = "GetInformationTagOfVersionResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagOfVersionResponse")
    public InformationTag getInformationTagOfVersion(
        @WebParam(name = "uri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String uri,
        @WebParam(name = "version", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Integer version);

    /**
     * 
     * @param getDeleted
     * @param targetUries
     * @return
     *     returns com.gratex.perconik.services.itm.ArrayOfstring
     */
    @WebMethod(operationName = "GetInformationTagsUri", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsUri")
    @WebResult(name = "GetInformationTagsUriResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagsUri", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUri")
    @ResponseWrapper(localName = "GetInformationTagsUriResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsUriResponse")
    public ArrayOfstring getInformationTagsUri(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted);

    /**
     * 
     * @param getDeleted
     * @param constraint
     * @param targetUries
     * @return
     *     returns com.gratex.perconik.services.itm.ArrayOfInformationTag
     */
    @WebMethod(operationName = "GetInformationTags", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTags")
    @WebResult(name = "GetInformationTagsResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTags", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTags")
    @ResponseWrapper(localName = "GetInformationTagsResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsResponse")
    public ArrayOfInformationTag getInformationTags(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "getDeleted", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean getDeleted,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint);

    /**
     * 
     * @param constraint
     * @param targetUries
     * @param onlyNewestVersions
     * @return
     *     returns com.gratex.perconik.services.itm.ArrayOfInformationTag
     */
    @WebMethod(operationName = "GetInformationTagsHistorically", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/GetInformationTagsHistorically")
    @WebResult(name = "GetInformationTagsHistoricallyResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "GetInformationTagsHistorically", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistorically")
    @ResponseWrapper(localName = "GetInformationTagsHistoricallyResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.GetInformationTagsHistoricallyResponse")
    public ArrayOfInformationTag getInformationTagsHistorically(
        @WebParam(name = "targetUries", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        ArrayOfstring targetUries,
        @WebParam(name = "constraint", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        InformationTagConstraint constraint,
        @WebParam(name = "onlyNewestVersions", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        Boolean onlyNewestVersions);

    /**
     * 
     * @param query
     * @return
     *     returns com.gratex.perconik.services.itm.ArrayOfArrayOfKeyValueOfstringRDFDataWYX0VZP7
     */
    @WebMethod(operationName = "ExecuteSparqlQuery", action = "http://perconik.fiit.stuba.sk/ITM/IITMaintenance/ExecuteSparqlQuery")
    @WebResult(name = "ExecuteSparqlQueryResult", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
    @RequestWrapper(localName = "ExecuteSparqlQuery", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQuery")
    @ResponseWrapper(localName = "ExecuteSparqlQueryResponse", targetNamespace = "http://perconik.fiit.stuba.sk/ITM", className = "com.gratex.perconik.services.itm.ExecuteSparqlQueryResponse")
    public ArrayOfArrayOfKeyValueOfstringRDFDataWYX0VZP7 executeSparqlQuery(
        @WebParam(name = "query", targetNamespace = "http://perconik.fiit.stuba.sk/ITM")
        String query);

}
